"""
docmax-demo Watch Mode
Monitors a directory for new files and automatically processes them.
"""

from __future__ import annotations

import time
from pathlib import Path

from docmax-demo.utils import abort, console, info, success, warn
from docmax-demo.config import (
    DEFAULT_OCR_LANG,
    SUPPORTED_IMAGE_EXTS,
    SUPPORTED_PDF_EXTS,
    WATCH_DEBOUNCE_SECONDS,
)


# ---------------------------------------------------------------------------
# Event handler
# ---------------------------------------------------------------------------

class _docmax-demoHandler:
    def __init__(self, action: str, lang: str, fmt: str):
        self.action = action
        self.lang = lang
        self.fmt = fmt
        self._seen: set = set()

    def dispatch(self, path: Path) -> None:
        if path in self._seen:
            return
        self._seen.add(path)

        time.sleep(WATCH_DEBOUNCE_SECONDS)

        if not path.exists():
            return

        ext = path.suffix.lower()

        # Ignore files generated by docmax-demo itself
        if any(path.stem.endswith(s) for s in (
            "_searchable", "_compressed", "_ocr", "_processed", "_deskewed",
            "_denoised", "_enhanced", "_watermarked", "_encrypted", "_decrypted",
        )):
            return

        if self.action == "ocr":
            allowed = SUPPORTED_IMAGE_EXTS | {".pdf"}
        elif self.action == "searchable":
            allowed = {".pdf"}
        elif self.action == "compress":
            allowed = {".pdf"}
        elif self.action == "preprocess":
            allowed = SUPPORTED_IMAGE_EXTS
        else:
            warn(f"Unknown watch action: {self.action}")
            return

        if ext not in allowed:
            return

        console.print(f"\n[bold cyan]→ Detected:[/bold cyan] {path.name}")

        try:
            if self.action == "ocr":
                from docmax-demo.engine import ocr_pdf, ocr_image
                if ext == ".pdf":
                    ocr_pdf(path, lang=self.lang, fmt=self.fmt)
                else:
                    ocr_image(path, lang=self.lang, fmt=self.fmt)

            elif self.action == "searchable":
                from docmax-demo.engine import make_searchable_pdf
                make_searchable_pdf(path, lang=self.lang)

            elif self.action == "compress":
                from docmax-demo.operations import compress
                compress(path)

            elif self.action == "preprocess":
                from docmax-demo.processor import preprocess_for_ocr
                preprocess_for_ocr(path)

        except Exception as exc:
            console.print(f"[red]Error processing {path.name}:[/red] {exc}")


# ---------------------------------------------------------------------------
# Watch entry point
# ---------------------------------------------------------------------------

def watch(
    directory: Path,
    action: str = "ocr",
    lang: str = DEFAULT_OCR_LANG,
    fmt: str = "txt",
) -> None:
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        abort("watchdog is required. Run: pip install watchdog")

    if not directory.exists():
        abort(f"Directory not found: {directory}")

    handler_state = _docmax-demoHandler(action=action, lang=lang, fmt=fmt)

    class _WatchdogBridge(FileSystemEventHandler):
        def on_created(self, event):
            if not event.is_directory:
                handler_state.dispatch(Path(event.src_path))

        def on_moved(self, event):
            if not event.is_directory:
                handler_state.dispatch(Path(event.dest_path))

    observer = Observer()
    observer.schedule(_WatchdogBridge(), str(directory), recursive=True)
    observer.start()

    console.print(
        f"\n[bold green]Watching[/bold green] [bold]{directory}[/bold] "
        f"(action: [cyan]{action}[/cyan])\n"
        "[dim]Press Ctrl+C to stop.[/dim]\n"
    )

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
        info("Watch mode stopped.")

    observer.join()
